### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PeterParslow**
Add link to SWG on OGC Portal

### CODE REVIEW

**Comment by ByronCinNZ** [comment]
Hello GeoDCAT team,

I propose that for the next two meetings, we stick to the every other Thursday at 700UTC. These would be on 12 and 26 October. 

If there are no objections to unanimous consent in the next three days, I will send meeting invites.

As the rest of the world adjusts their clocks, we may want to revisit this decision. 
It is very difficult to find a time to suit al SWG members. Currently, North America suffers the most by these timings. We could think of shifting to 2000UTC in November which would make the timings as follows:
	7:00am Sydney
	9:00pm Brussels
	3:00pm New York
Would this be agreeable?

Cheers,


Byron Cochrane
￼
OpenWork Ltd
Nelson, New Zealand
***@***.***
+64 21 794 501
https://www.openwork.nz/

“The whole problem with the world is that fools and fanatics are so certain of themselves, yet wiser people so full of doubt” - Bertrand Russell
"Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.” - Margaret Mead

**Comment by PeterParslow** [comment]
Byron,
I can make the 12th but not the 26th (two weeks’ leave). I’m happy with the proposed timing from November (8pm my time).
Peter

**Comment by ByronCinNZ** [comment]
Reminder of tomorrow’s meeing and connection detail.

Danny will be providing a agenda shortly

The next GeoDCAT SWG meeting will be at UTC 0700 12 Oct. (Check your calendars for DayLite Svaings changes!)

GoTo Meeting details -

OGC GeoDCAT SWG


Please join my meeting from your computer, tablet or smartphone.
https://meet.goto.com/791037533

You can also dial in using your phone.
Access Code: 791-037-533
United States: +1 (224) 501-3412 <tel:+12245013412,,791037533>


Join from a video-conferencing room or system.
Meeting ID: 791-037-533
Dial in or type: 67.217.95.2 or inroomlink.goto.com <http://inroomlink.goto.com/>
Or dial directly: ***@***.*** ***@***.***> or 67.217.95.2##791037533


Get the app now and be ready when your first meeting starts:
https://meet.goto.com/install

**Comment by ByronCinNZ** [comment]
Hello,

Thank you for your patience with us, but the world seems to have had tother plans for both Danny and me today. 

So we will sadly need to cancel this SWG meeting. 

We will reconvene in two weeks at the same time on 26 October.

Cheers,


Byron Cochrane
￼
OpenWork Ltd
Nelson, New Zealand
***@***.***
+64 21 794 501
https://www.openwork.nz/

“The whole problem with the world is that fools and fanatics are so certain of themselves, yet wiser people so full of doubt” - Bertrand Russell
"Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.” - Margaret Mead

**Review by ByronCinNZ — APPROVED** [review]

**Review by ByronCinNZ — APPROVED** [review]

**Pull request merged**
